tileshp: ./shp_preparation/sentinel2_tiles_world/sentinel2_tiles_world


platform: 'modis'

# Process only files with less than xx % cloudcover
maxcloudcover: 10

# Extract files with xx m pixel size 
# options: 250, 500, 1000
pixelsize: 250

# Values to be to be included in cloudmask
# default [9,8,3,10,0,1]
tobemaskedlist: 
  - 9 # cloud high probability
  - 8 # cloud medium probability
  - 3 # cloud shadow
  - 10 # cirrus
  - 0 # no data
  - 1 # saturated and defective

# path towards bands
bandlocation: ./*/*/IMG_DATA/

#indicator for cloudfile
cloudfilename: 'SCL'

# Sentinel-2 bands
red : 'B04'
green: 'B03'
blue: 'B02'
nir: 'B08'
r_edge: 'B05'
swir1: 'B11'
swir2: 'B12'


tilepattern: '(?<=T)[0-9]{2}[A-Z]{3}'

#the first that is found is used
datepattern: '20[1-2][0-9][0-1][0-9][0-3][0-9]'

band_designation: 'B[0-1]?\dA?'

# Quantification value used to multiple the reflectance to get DN
# This could be read from metadata but for now at least is here
quantification_value: 10000

# available resolutions per band
B01: [60]
B02: [10,20,60]
B03: [10,20,60]
B04: [10,20,60]
B05: [20,60]
B06: [20,60]
B07: [20,60]
B08: [10]
B8A: [20,60]
B09: [60]
B11: [20,60]
B12: [20,60]
SCL: [20,60]
AOT: [10,20,60]
TCI: [10,20,60]
WVP: [10,20,60]

#upsampling 
#available: 'biliner'

upsampling_method: 'bilinear'

#downsampling
#available: 'bilinear'

downsampling_method: 'bilinear'



