####

# Configuration file for the use of Sentinel-2 #

# Know what you do before you change anything here #

####

# Enter platform name
platform: 's2'

# Enter (smallest) pixelsize (10 m for Sentinel-2)
pixelsize: 10

# Process only files with less than xx % cloudcover
maxcloudcover: 99

# Mask conditions are stored as values, not as bitflags
bitmask: 0

# Values to be to be included in cloudmask
# default [9,8,3,10,0,1]
tobemaskedlist: 
  - 9 # cloud high probability
  - 8 # cloud medium probability
  - 3 # cloud shadow
  - 10 # cirrus
  - 0 # no data
  - 1 # saturated and defective

#pattern to find all data files
filepattern: 'S2[A-C]_MSIL2A_\d{8}T\d{6}_N\d{4}_R\d{3}_T\d{2}[A-Z]{3}_\d{8}T\d{6}.SAFE$'

# Sentinel-2 bands
red : 'B04'
green: 'B03'
blue: 'B02'
nir: 'B08'
r_edge: 'B05'
swir1: 'B11'
swir2: 'B12'
8A: 'B8A'
coastal: 'B01'

# some part of the products file name that identifies them as product to be used
productnameidentifier: 'S2*.SAFE'

# parts to build path towards bands
bandlocation: ['.','*','*','IMG_DATA']

# path building set after imgpath to get the bandfile
pathbuildinglist: ['R', 'pixelsize' , 'm','*', 'bandname', '_' , 'pixelsize' ,'m.jp2']

#indicator for cloudfile
cloudfilename: 'SCL'

tilepattern: '(?<=T)[0-9]{2}[A-Z]{3}'

#the first that is found is used
datepattern: '20[1-2][0-9][0-1][0-9][0-3][0-9]'

band_designation: 'B[0-1]?\dA?'

# Quantification value used to multiple the reflectance to get DN
# This could be read from metadata but for now at least is here
quantification_value: 10000

# available resolutions per band
B01: [60]
B02: [10,20,60]
B03: [10,20,60]
B04: [10,20,60]
B05: [20,60]
B06: [20,60]
B07: [20,60]
B08: [10]
B8A: [20,60]
B09: [60]
B11: [20,60]
B12: [20,60]
SCL: [20,60]
AOT: [10,20,60]
TCI: [10,20,60]
WVP: [10,20,60]

# Lookup table for storing the tiles and the IDs they include for every tile processed by EODIE with --array_out
# Table needed for array plotting
lookup: '../postprocesses/lookuptable.txt'

# Enter resampling method
resampling_method: 'bilinear'
