#location of Sentinel2-tiles-world shapefile
tileshp: ./sentinel2_tiles_world/sentinel2_tiles_world

#name of field where tilenames are stored in shapefile
fieldname: 'Name'

platform: 's2'

# Process only files with less than xx % cloudcover
maxcloudcover: 10

# Extract files with xx m pixel size 
# options: 10,20,(60)
pixelsize: 10

bitmask: 0

# Values to be to be included in cloudmask
# default [9,8,3,10,0,1]
tobemaskedlist: 
  - 9 # cloud high probability
  - 8 # cloud medium probability
  - 3 # cloud shadow
  - 10 # cirrus
  - 0 # no data
  - 1 # saturated and defective

# parts to build path towards bands
bandlocation: ['.','*','*','IMG_DATA']


#indicator for cloudfile
cloudfilename: 'SCL'

# Sentinel-2 bands
red : 'B04'
green: 'B03'
blue: 'B02'
nir: 'B08'
r_edge: 'B05'
swir1: 'B11'
swir2: 'B12'


tilepattern: '(?<=T)[0-9]{2}[A-Z]{3}'

#the first that is found is used
datepattern: '20[1-2][0-9][0-1][0-9][0-3][0-9]'

band_designation: 'B[0-1]?\dA?'

# Quantification value used to multiple the reflectance to get DN
# This could be read from metadata but for now at least is here
quantification_value: 10000

# available resolutions per band
B01: [60]
B02: [10,20,60]
B03: [10,20,60]
B04: [10,20,60]
B05: [20,60]
B06: [20,60]
B07: [20,60]
B08: [10]
B8A: [20,60]
B09: [60]
B11: [20,60]
B12: [20,60]
SCL: [20,60]
AOT: [10,20,60]
TCI: [10,20,60]
WVP: [10,20,60]

#upsampling (converting to higher resolution/smaller cells)
#available: 'biliner','nearest','cubic','average', ...
# from https://rasterio.readthedocs.io/en/latest/api/rasterio.enums.html#rasterio.enums.Resampling

resampling_method: 'bilinear'

#downsampling (converting to lower resolution/larger cellsize)
#available: 'bilinear','nearest','cubic','average', ...
# from https://rasterio.readthedocs.io/en/latest/api/rasterio.enums.html#rasterio.enums.Resampling

downsampling_method: 'bilinear'

# path building set *after inpath* to get the bandfile

pathbuildinglist: ['R', 'pixelsize' , 'm','*', 'bandname', '_' , 'pixelsize' ,'m.jp2']

# Testing....

